config/routes.rb
Rails.application.routes.draw do
  resources :skill_sets
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }


  resource :users do
    get 'profile'
    member do
      put 'update_profile'
    end
  end

  resources :homes
  resources :job_posts do
    member do
      post 'apply'
    end
  end
  resources :business_streams
  resources :job_types
  resources :companies
  resources :user_types
  root to: 'job_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_stream.rb
class BusinessStream < ApplicationRecord
  has_many :companies

  validates :name, :presence => true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :stream, foreign_key: 'business_stream_id', class_name: 'BusinessStream'

  validates :name,:presence => true
  validates :profile_description,:presence => true
  validates :business_stream_id,:presence => true
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord
  belongs_to :user
  validates :cerficate_degree_name, :presence => true
  validates :user_id, :presence => true
end

app/models/experience_detail.rb
class ExperienceDetail < ApplicationRecord
  belongs_to :user
  validates :user_id, :presence => true
  validates :company_name, :presence => true
  validates :job_location_city, :presence => true
end

app/models/job_location.rb
class JobLocation < ApplicationRecord
end

app/models/job_post.rb
class JobPost < ApplicationRecord
  include JobPostConcern

  validates :user_id, :presence => true
  validates :job_title, :presence => true

  accepts_nested_attributes_for :job_location

  delegate :name, :to => :company
  delegate :website_url, :to => :company
  delegate :city, :to => :job_location
end

app/models/job_post_activity.rb
class JobPostActivity < ApplicationRecord
  validates :user_id, :presence => true
  validates :job_post_id, :presence => true
  validates :apply_date, :presence => true

  belongs_to :job_post

  def self.new_activity(job_post, user)
    JobPostActivity.create({user_id: user.id, job_post_id: job_post.id, apply_date: Date.today})
  end
end

app/models/job_post_skill_set.rb
class JobPostSkillSet < ApplicationRecord
  belongs_to :job_post
end

app/models/job_type.rb
class JobType < ApplicationRecord
  validates_length_of :job_type_name, :presence => true, :maximum => 25, :allow_blank => false
  has_many :job_posts
end

app/models/seeker_profile.rb
class SeekerProfile < ApplicationRecord
  belongs_to :user
  validates :first_name, :presence => true
  validates :last_name, :presence => true
end

app/models/seeker_skill_set.rb
class SeekerSkillSet < ApplicationRecord
  belongs_to :user
  belongs_to :skill_set
  validates :user_id, :presence => true
  validates :skill_set_id, :presence => true
end

app/models/skill_set.rb
class SkillSet < ApplicationRecord
  has_many :seeker_skill_sets
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :seeker_profiles, :dependent => :destroy, inverse_of: :user
  has_many :education_details, :dependent => :destroy, inverse_of: :user
  has_many :experience_details, :dependent => :destroy, inverse_of: :user
  has_many :seeker_skill_sets, :dependent => :destroy, inverse_of: :user

  accepts_nested_attributes_for :seeker_profiles, :education_details, :experience_details, :seeker_skill_sets, allow_destroy: true
end

app/models/user_type.rb
class UserType < ApplicationRecord
  validates_length_of :name, :presence => true, :maximum => 25, :allow_blank => false
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  before_action :set_job_post, only: [:edit, :show, :update, :destroy, :apply]

  def index
  end

  def show
  end

  def new
    @job_post = JobPost.new
    @job_post.build_job_location
  end

  def apply
    if current_user.present?
      if JobPostActivity.new_activity(@job_post, current_user)
        puts 'done'
      else
        render @job_post, notice: @job_post.errors
      end
    else
      redirect_to new_user_session_path, notice: 'You need to SignIn before apply for the Job'
    end
  end

  def edit
    @job_post.job_location
  end

  def create
    @job_post = JobPost.new(job_post_params)

    if @job_post.save
      redirect_to job_posts_path, notice: 'Job post added successfully!'
    else
      render 'new'
    end
  end

  def update
    if @job_post.update_attributes(job_post_params)
      redirect_to @job_post, notice: 'JobPost updated successfully'
    else
      render 'edit', notice: @job_post.errors
    end
  end

  def destroy
  end

  private

  def set_job_post
    @job_post = JobPost.find(params[:id])
  end

  def job_post_params
    params.require(:job_post).permit(:job_title, :user_id, :exp_required, :salary, :job_type_id, :company_id, :is_company_name_hidden, :job_description, :job_location_id, :is_active, :key_skills => [], :job_location_attributes => [:id, :street_address, :city, :state, :country, :zip])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
  def is_post_user_current_user_same(job)
    job.user_id == current_user.id if current_user.present?
  end
  
  def if_current_user_is_recruiter
    current_user&.user_type_id == 2
  end
end

app/helpers/job_types_helper.rb
module JobTypesHelper
end

app/helpers/skill_sets_helper.rb
module SkillSetsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/job_posts/_form.html.haml
.col-lg-6.col-lg-offset-3
  .panel.panel-default
    .panel-body
      = simple_form_for(@job_post) do |f|
        = f.error_notification
        .form-inputs
          = f.input :job_title
          = f.input :job_type_id, collection: JobType.all.map{|u| [u.job_type_name, u.id]}, include_blank: true
          = f.input :company_id, collection: Company.all.map{|u| [u.name, u.id]}, include_blank: true
          = f.input :is_company_name_hidden
          = f.input :job_description
          = f.input :is_active
          = f.input :exp_required
          = f.input :key_skills, collection: SkillSet.all.map{|s| [s.skill_set_name, s.id]}, input_html: { multiple: true }
          = f.input :salary
          = f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
        .form-inputs
          = f.simple_fields_for :job_location do |sp|
            = sp.input :street_address
            = sp.input :city
            = sp.input :state
            = sp.input :country, :as => :string
            = sp.input :zip
        .form-actions
          = f.button :submit, "Save"

app/views/job_posts/_job.html.haml
.panel.panel-default
  .panel-body
    .col-lg-12.no-padding
      .col-lg-12.no-padding
        - if user_signed_in?
          - if is_post_user_current_user_same(job)
            %b= link_to job.job_title, edit_job_post_path(job)
          - else
            %b= link_to job.job_title, job_post_path(job)
        - else
          %b= link_to job.job_title, job_post_path(job)
      .col-lg-12.no-padding
        .label.label-default= "#{job.job_title} years"
      .col-lg-3.no-padding.fa.fa-suitcase
        %span= "#{job.exp_required} Years"
      .col-lg-3.no-padding.fa.fa-location-arrow
        = job.city
    .col-lg-3.no-padding
      Key Skills:
    .col-lg-3.no-padding
      Testing  
  .panel-footer
    .col-lg-3.no-padding.fa.fa-inr
      %span.fa.fa-heart.pull-left
      = job.salary
    .col-lg-3.no-padding.glyphicon.glyphicon-user
      PostedBy
    .col-lg-3.no-padding
      Test
    .col-lg-3.no-padding
      = time_ago_in_words(job.created_at) + ' ago'

app/views/job_posts/_side_panel.html.haml
.col-lg-3.col-lg-offset-1
  .panel.panel-default
    .panel-body
      .col-lg-12
        Find Jobs For
      .col-lg-12
        %hr
          Testing
      .col-lg-12
        %hr
          Skills
  .panel.panel-default
    .panel-body
      .col-lg-12
        Refine Results
      .col-lg-12
        %hr
          Freshness
      .col-lg-12
        %hr
          .dropdown
            %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
              Dropdown
              %span.caret
            %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Separated link
      .col-lg-12
        %hr
          .dropdown
            %button#dropdownMenu2.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
              Dropdown
              %span.caret
            %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu2"}
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Separated link

app/views/job_posts/create.html.haml
%h1 JobPosts#create
%p Find me in app/views/job_posts/create.html.haml

app/views/job_posts/destroy.html.haml
%h1 JobPosts#destroy
%p Find me in app/views/job_posts/destroy.html.haml

app/views/job_posts/edit.html.haml
= render 'form'

app/views/job_posts/index.html.haml
= render 'side_panel'
-if job_posts.blank?
  .col-lg-6
    = 'No Jobs found'
- else
  .col-lg-6
    - job_posts.each do |job|
      = render partial: 'job', locals: {job: job}
.row
  .col-lg-3
    - if if_current_user_is_recruiter
      = link_to "Add New Job", new_job_post_path, class: 'btn btn-default'
      = link_to "Back", root_path, class: 'btn btn-default'

app/views/job_posts/new.html.haml
= render 'form'

app/views/job_posts/show.html.haml
.col-lg-9
  .panel.panel-default
    .panel-body
      .col-lg-12.no-padding
        .col-lg-12.no-padding
          %b= @job_post.job_title.blank? ? 'Test' : @job_post.job_title
        .col-lg-12.no-padding
          = link_to @job_post.name, @job_post.website_url
        .col-lg-3.no-padding.fa.fa-suitcase
          %span= "#{@job_post.exp_required} Years"
        .col-lg-3.no-padding.fa.fa-location-arrow
          = link_to @job_post.city, root_path, title: "Web Developer Jobs in  #{@job_post.city}"
        .col-lg-12.no-padding
          %br
            %p
              - if @job_post.activities.first && is_post_user_current_user_same(@job_post)
                %p.fa.fa-check= "You already applied this job on #{@job_post.activities.first.apply_date.strftime("%e %b")}"
              - else
                = link_to "Apply", apply_job_post_path(@job_post.id), method: :post, class: 'btn btn-sm btn-primary'
    .panel-footer
      .col-lg-3.no-padding.fa.fa-inr
        %span.fa.fa-heart.pull-left
        = @job_post.salary
      .col-lg-3.no-padding.glyphicon.glyphicon-user
        PostedBy
      .col-lg-3.no-padding
        Test
      .col-lg-3.no-padding
        = time_ago_in_words(@job_post.created_at) + ' ago'
  .panel.panel-default
    .panel-body
      .col-lg-12.no-padding
        %p Job Description
        = @job_post.job_description

app/views/job_posts/update.html.haml
%h1 JobPosts#update
%p Find me in app/views/job_posts/update.html.haml