config/routes.rb
Rails.application.routes.draw do
  resources :skill_sets
  devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
  }


  resource :users do
    get 'profile'
    member do
      put 'update_profile'
    end
  end

  resources :homes
  resources :job_posts do
    member do
      post 'apply'
    end
  end
  resources :business_streams
  resources :job_types
  resources :companies
  resources :user_types
  root to: 'job_posts#index'
end

app/models/business_stream.rb
class BusinessStream < ApplicationRecord
  has_many :companies

  validates :name, :presence => true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :stream, foreign_key: 'business_stream_id', class_name: 'BusinessStream'

  validates :name,:presence => true
  validates :profile_description,:presence => true
  validates :business_stream_id,:presence => true
end

app/models/education_detail.rb
class EducationDetail < ApplicationRecord
  belongs_to :user
  validates :cerficate_degree_name, :presence => true
  validates :user_id, :presence => true
end

app/models/experience_detail.rb
class ExperienceDetail < ApplicationRecord
  belongs_to :user
  validates :user_id, :presence => true
  validates :company_name, :presence => true
  validates :job_location_city, :presence => true
end

app/models/job_location.rb
class JobLocation < ApplicationRecord
end

app/models/job_post.rb
class JobPost < ApplicationRecord
  include JobPostConcern

  validates :user_id, :presence => true
  validates :job_title, :presence => true

  accepts_nested_attributes_for :job_location

  delegate :name, :to => :company
  delegate :website_url, :to => :company
  delegate :city, :to => :job_location
end

app/models/job_post_activity.rb
class JobPostActivity < ApplicationRecord
  validates :user_id, :presence => true
  validates :job_post_id, :presence => true
  validates :apply_date, :presence => true

  belongs_to :job_post

  def self.new_activity(job_post, user)
    JobPostActivity.create({user_id: user.id, job_post_id: job_post.id, apply_date: Date.today})
  end
end

app/models/job_type.rb
class JobType < ApplicationRecord
  validates_length_of :job_type_name, :presence => true, :maximum => 25, :allow_blank => false
  has_many :job_posts
end

app/models/seeker_profile.rb
class SeekerProfile < ApplicationRecord
  belongs_to :user
  validates :first_name, :presence => true
  validates :last_name, :presence => true
end

app/models/seeker_skill_set.rb
class SeekerSkillSet < ApplicationRecord
  belongs_to :user
  belongs_to :skill_set
  validates :user_id, :presence => true
  validates :skill_set_id, :presence => true
end

app/models/skill_set.rb
class SkillSet < ApplicationRecord
  has_many :seeker_skill_sets
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :seeker_profiles, :dependent => :destroy, inverse_of: :user
  has_many :education_details, :dependent => :destroy, inverse_of: :user
  has_many :experience_details, :dependent => :destroy, inverse_of: :user
  has_many :seeker_skill_sets, :dependent => :destroy, inverse_of: :user

  accepts_nested_attributes_for :seeker_profiles, :education_details, :experience_details, :seeker_skill_sets, allow_destroy: true
end

app/models/user_type.rb
class UserType < ApplicationRecord
  validates_length_of :name, :presence => true, :maximum => 25, :allow_blank => false
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
  def is_post_user_current_user_same(job)
    job.user_id == current_user.id if current_user.present?
  end
  
  def if_current_user_is_recruiter
    current_user&.user_type_id == 2
  end
end

app/helpers/job_types_helper.rb
module JobTypesHelper
end

app/helpers/skill_sets_helper.rb
module SkillSetsHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-2", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#{root_path}"} Jobs For You
    #bs-example-navbar-collapse-2.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "#"}
            Link
            %span.sr-only (current)
        %li
          %a{:href => "#"} Link
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Jobs
          %ul.dropdown-menu{:role => "menu"}
            %li
              = link_to 'Jobs', job_posts_path
            %li
              = link_to 'Companies', companies_path
            %li
              = link_to 'Business Stream', business_streams_path
            %li.divider
            %li
              = link_to 'Skill Set', skill_sets_path
            %li.divider
            %li
              = link_to 'JobTypes', job_types_path
          -#%form.navbar-form.navbar-left{:role => "search"}
          -#  .form-group
          -#    %input.form-control{:placeholder => "Search", :type => "text"}/
          -#  %button.btn.btn-default{:type => "submit"} Submit
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          %li
            = link_to 'Sign In', new_user_session_path
          %li
            = link_to 'Sign Up', homes_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.email
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to "Update Profile", profile_users_path
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider
              %li
                %a{:href => "#"} Separated link
              %li.divider
              %li
                %a{:href => "#"} One more separated link

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title JobPortal
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/navbar'
    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert alert-info"
      = yield